Merge Authentication Feature into Development
benzybert/tea-haven-backend pull request #3
Opened 2024-12-24 11:35 UTC by benzybert

## Feature: Authentication Implementation

### Changes Included
- Implemented authentication routes and logic
- Consolidated database connection configuration
- Removed redundant database configuration file

### Key Updates
- Added authentication-related routes in `routes/auth.js`
- Streamlined database connection setup
- Removed unnecessary `config/db.js`

### Testing Recommendations
- Verify authentication endpoints
- Test database connection
- Ensure all authentication flows work as expected

### Notes
- Database connection now managed directly in `server.js`
- Simplified project structure

2024-12-24 23:04 UTC, alesha712 requested changes
I can see you copied all files - but you also copied old version of them. Make sure you follow the structre : route -> controller -> service 
The service should comunicate with a "repository" layer - this layer is responsible for the api and database operations. 
So, for DB operations, you should create a "dbRepository.js" file in a "repository" directory. this file will be responsible for performing CRUD operations.

2024-12-24 23:04 UTC, alesha712 commented on config/db.js
Why did you remove this file? 
You moved this logic back to server.js - making server.js messier

2024-12-24 23:04 UTC, alesha712 commented on controllers/authController.js
The controller should manage only request / response - without any business logic, api calls or database operations. 
You should create a service for auth operation - that is where you'll have the business logic. 
The controller will then call the service to perform the logic of the authentication. 
We need to discuss it.

2024-12-24 23:04 UTC, alesha712 commented on controllers/teaController.js
It seems like you copy pasted an old version of the file - we already discussed it and you already changed it (see the 'development' branch in the old repository).

2024-12-24 23:04 UTC, alesha712 commented on server.js
> -connectDB();
You used an old version of this file - you have already updated it with a better structure (see 'development' bracnh in the old repository).

2024-12-25 12:52 UTC, benzybert commented on config/db.js
I didnt fully understand its funcationalty, since server.js is pretty clean and handles the logic, so ive decided to delete.

2024-12-25 12:53 UTC, benzybert commented on config/db.js
In terms of seperation of concerns, I agree its better to move some code to config/db.js.
will do.

2024-12-25 12:57 UTC, benzybert commented on config/db.js
changed to:
// Connect to MongoDB
connectDB();

and moved some of the logic to config/db.js

2024-12-25 13:25 UTC, benzybert commented on controllers/teaController.js
yes. added.

2024-12-25 13:27 UTC, benzybert commented on server.js
> -connectDB();
yes, I maybe copied the wrong branch :(  . fixed.

2025-01-09 13:50 UTC, merged